apiVersion: v1
kind: Service
metadata:
  name: ist-trading-api
  namespace: ist-trading
  labels:
    app: intelligent-strategy-trading
    component: api
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http-api
      name: api-http
  selector:
    app: intelligent-strategy-trading
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: ist-monitor
  namespace: ist-trading
  labels:
    app: intelligent-strategy-trading
    component: monitor
    tier: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-monitor
      name: monitor-http
  selector:
    app: intelligent-strategy-trading
    component: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: ist-dashboard
  namespace: ist-trading
  labels:
    app: intelligent-strategy-trading
    component: dashboard
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-dash
      name: dash-http
  selector:
    app: intelligent-strategy-trading
    component: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: ist-trading-api-lb
  namespace: ist-trading
  labels:
    app: intelligent-strategy-trading
    component: api
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: api-http
      name: api-lb-http
  selector:
    app: intelligent-strategy-trading
    component: api